
# gallus_gallus to podarcis_muralis(only Z)
~/Soft/MAVR/scripts/wga/dotplot_from_last_tab.py -i gallus_gallus.to.podarcis_muralis.db_YASS_R01_no_soft.R01.one_to_one.potsmasked.tab -w NC_041330.1 -x ~/data/genomes/gallus_gallus/ncbi/GRCg6a/gallus_gallus.chr.ids -s ~/data/genomes/gallus_gallus/ncbi/GRCg6a/gallus_gallus.chr.syn  --query_syn_file_key_column 1 --query_syn_file_value_column 0 -y ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.syn --target_syn_file_key_column 1 --target_syn_file_value_column 0 -l "Podarcis muralis" -r "Gallus gallus" --format tab_mismap -u chrZ -z chr17,chr4,ch1,chr2,chr3,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20 -o gallus_gallus.to.podarcis_muralis.db_YASS_R01_no_soft.R01.one_to_one.potsmasked.onlyZ.12x12 -f 4,12 --linewidth 1

# gallus_gallus to podarcis_muralis(figsize 12x12 linewidth 0.5)
~/Soft/MAVR/scripts/wga/dotplot_from_last_tab.py -i gallus_gallus.to.podarcis_muralis.db_YASS_R01_no_soft.R01.one_to_one.potsmasked.tab -w ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.ids -x ~/data/genomes/gallus_gallus/ncbi/GRCg6a/gallus_gallus.chr.ids -s ~/data/genomes/gallus_gallus/ncbi/GRCg6a/gallus_gallus.chr.syn  --query_syn_file_key_column 1 --query_syn_file_value_column 0 -y ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.syn --target_syn_file_key_column 1 --target_syn_file_value_column 0 -l "Podarcis muralis" -r "Gallus gallus" --format tab_mismap -u ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr -z chr5,chr7,chr18,chr13,chr12,chr3,chr1,chr6,chr9,chr8,chr26,chr20,chr2,chr23,chr11,chr21,chr4,chrZ,chr27,chr10,chr14,chr19,chr24,chr22,chr15,chr28,chr17 -o gallus_gallus.to.podarcis_muralis.db_YASS_R01_no_soft.R01.one_to_one.potsmasked.ordered.12x12 -f 12,12 --linewidth 0.5

# gallus_gallus to podarcis_muralis(figsize 24x24 linewidth 0.5)
 ~/Soft/MAVR/scripts/wga/dotplot_from_last_tab.py -i gallus_gallus.to.podarcis_muralis.db_YASS_R01_no_soft.R01.one_to_one.potsmasked.tab -w ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.ids -x ~/data/genomes/gallus_gallus/ncbi/GRCg6a/gallus_gallus.chr.ids -s ~/data/genomes/gallus_gallus/ncbi/GRCg6a/gallus_gallus.chr.syn  --query_syn_file_key_column 1 --query_syn_file_value_column 0 -y ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.syn --target_syn_file_key_column 1 --target_syn_file_value_column 0 -l "Podarcis muralis" -r "Gallus gallus" --format tab_mismap -u ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr -z chr5,chr7,chr18,chr13,chr12,chr3,chr1,chr6,chr9,chr8,chr26,chr20,chr2,chr23,chr11,chr21,chr4,chrZ,chr27,chr10,chr14,chr19,chr24,chr22,chr15,chr28,chr17 -o gallus_gallus.to.podarcis_muralis.db_YASS_R01_no_soft.R01.one_to_one.potsmasked.ordered.24x24 -f 24,24 --linewidth 0.5

# lacerta viridis to podarcis muralis
 ~/Soft/MAVR/scripts/wga/dotplot_from_last_tab.py -i lacerta_viridis.to.podarcis_muralis.tab -w NC_041330.1  -x ~/data/genomes/lacerta_viridis/ncbi/ASM90024590v1/lacerta_viridis.1Mplus.ids  -y ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.syn --target_syn_file_key_column 1 --target_syn_file_value_column 0 -l "Podarcis muralis" -r "Lacerta viridis" --format tab_mismap -u chrZ -o lacerta_viridis.to.podarcis_muralis.onlyZ.1Mplus -f 3,12 --linewidth 0.5 --hide_grid

~/Soft/MAVR/scripts/wga/dotplot_from_last_tab.py -i lacerta_viridis.to.podarcis_muralis.one_to_one.tab -w NC_041330.1  -x ~/data/genomes/lacerta_viridis/ncbi/ASM90024590v1/lacerta_viridis.1Mplus.ids  -y ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.syn --target_syn_file_key_column 1 --target_syn_file_value_column 0 -l "Podarcis muralis" -r "Lacerta viridis" --format tab_mismap -u chrZ -o lacerta_viridis.to.podarcis_muralis.one_to_one.onlyZ.1Mplus -f 3,12 --linewidth 0.5 --hide_grid


~/Soft/MAVR/scripts/wga/dotplot_from_last_tab.py -i lacerta_viridis.to.podarcis_muralis.one_to_one.tab -w NC_041330.1 -z ~/data/genomes/lacerta_viridis/ncbi/ASM90024590v1/lacerta_viridis.ids  -y ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.syn --target_syn_file_key_column 1 --target_syn_file_value_column 0 -l "Podarcis muralis" -r "Lacerta viridis" --format tab_mismap -u chrZ -o lacerta_viridis.to.podarcis_muralis.one_to_one.onlyZ.all -f 3,12 --linewidth 0.5 --hide_grid --hide_query_labels

~/Soft/MAVR/scripts/wga/dotplot_from_last_tab.py -i lacerta_viridis.to.podarcis_muralis.one_to_one.tab -w NC_041330.1 -z ~/data/genomes/lacerta_viridis/ncbi/ASM90024590v1/lacerta_viridis.ids  -y ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.syn --target_syn_file_key_column 1 --target_syn_file_value_column 0 -l "Podarcis muralis" -r "Lacerta viridis" --format tab_mismap -u chrZ -o lacerta_viridis.to.podarcis_muralis.one_to_one.onlyZ.all -f 5,12 --linewidth 0.5 --hide_grid --hide_query_labels --left_offset 0.25 --right_offset 0.75
~/Soft/MAVR/scripts/wga/dotplot_from_last_tab.py -i lacerta_viridis.to.podarcis_muralis.one_to_one.tab -w NC_041330.1 -z ~/data/genomes/lacerta_viridis/ncbi/ASM90024590v1/lacerta_viridis.ids  -y ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.syn --target_syn_file_key_column 1 --target_syn_file_value_column 0 -l "Podarcis muralis" -r "Lacerta viridis" --format tab_mismap -u chrZ -o lacerta_viridis.to.podarcis_muralis.one_to_one.onlyZ.all.12x12 -f 12,12 --linewidth 0.5 --hide_grid --hide_query_labels --left_offset 0.15 --right_offset 0.85
~/Soft/MAVR/scripts/wga/dotplot_from_last_tab.py -i lacerta_viridis.to.podarcis_muralis.one_to_one.tab -w NC_041330.1 -z ~/data/genomes/lacerta_viridis/ncbi/ASM90024590v1/lacerta_viridis.ids  -y ~/data/genomes/podarcis_muralis/ncbi/PodMur_1.0/podarcis_muralis.chr.syn --target_syn_file_key_column 1 --target_syn_file_value_column 0 -l "Podarcis muralis" -r "Lacerta viridis" --format tab_mismap -u chrZ -o lacerta_viridis.to.podarcis_muralis.one_to_one.onlyZ.all.12x12.visible_x -f 12,12 --linewidth 0.5 --hide_grid --hide_query_labels --left_offset 0.15 --right_offset 0.85 --x_axis_visible
