__author__ = 'mahajrod'

from RouToolPa.Collections.General import SynDict


mithochondrioal_genes_syndict = SynDict({"12S_rRNA":
                                            ["12S_rRNA",
                                             "12S rRNA",
                                             "12S ribosomal RNA",
                                             "small subunit ribosomal RNA",
                                             "s-rRNA", "s-rRNA; 12S ribosomal RNA",
                                             "small ribosomal RNA subunit RNA",
                                             "12S ribosomal RNA",
                                             "12S ribosomal RNA subunit",
                                             "12S rivbosomal RNA",
                                             "12S ribosamal RNA",
                                             "l2S ribosomal RNA",
                                             "12 ribosomal RNA",
                                             "12S ribosormal RNA,"
                                             "12 rRNA",
                                             "s-RNA"],
                                         "16S_rRNA":
                                            ["16S_rRNA",
                                             "16S rRNA",
                                             "16S ribosomal RNA",
                                             "large subunit ribosomal RNA",
                                             "l-rRNA",
                                             "l-rRNA; 16S ribosomal RNA",
                                             "large ribosomal RNA subunit RNA",
                                             "16S ribosomal RNA",
                                             "16S ribosomal RNA subunit",
                                             "16S rivbosomal RNA",
                                             "16S ribosamal RNA",
                                             "l6S ribosomal RNA",
                                             "16 ribosomal RNA",
                                             "16S ribosormal RNA",
                                             "16 rRNA",
                                             "l-RNA"],
                                         "ATP6":
                                            ["ATP6",
                                             "atp6",
                                             "ATPase6",
                                             "ATPase 6",
                                             "ATPase subunit 6",
                                             "ATP synthase F0 subunit 6",
                                             "ATP synthetase F0 subunit 6",
                                             "ATP synthase subunit 6"
                                             "ATPase subunits 6",
                                             "adenosine triphosphatase subunit 6",
                                             "ATPase subunit-6"],
                                         "ATP8":
                                            ["ATP8",
                                             "atp8",
                                             "ATPase8",
                                             "ATPase 8",
                                             "ATPase subunit 8",
                                             "ATP synthase F0 subunit 8",
                                             "ATP synthetase F0 subunit 8",
                                             "ATP synthase subunit 8",
                                             "ATPase subunits 8",
                                             "adenosine triphosphatase subunit 8",
                                             "adenosine triphosphate subunit 8",
                                             "ATPase subunit-8"],
                                         "COX1":
                                            ["COX1", "COXI",
                                             "cytochrome c oxidase subunit 1",
                                             "cytochrome c oxidase subunit I",
                                             "Cytochrome c oxidase subunit 1",
                                             "cytochrome oxidase subunit I",
                                             "chytochrome c oxidase subunit I",
                                             "COI",
                                             "CO1", "CO 1", "CO I", "coi",
                                             "product: cytochrome c oxidase subunit I",
                                             "cytochrome oxidase subunit 1"],
                                         "COX2":
                                            ["COX2", "COXII",
                                             "cytochrome c oxidase subunit 2",
                                             "cytochrome c oxidase subunit II",
                                             "Cytochrome c oxidase subunit 2",
                                             "cytochrome oxidase subunit II",
                                             "chytochrome c oxidase subunit II",
                                             "COII",
                                             "CO2", "CO 2", "CO II", "coii",
                                             "cytochrome oxidase subunit 2"],
                                         "COX3":
                                            ["COX3", "COXIII",
                                             "cytochrome c oxidase subunit 3",
                                             "cytochrome c oxidase subunit III",
                                             "Cytochrome c oxidase subunit 3",
                                             "cytochrome oxidase subunit III",
                                             "chytochrome c oxidase subunit III",
                                             "COIII",
                                             "CO3", "CO 3", "CO III", "coiii",
                                             "cytochrome oxidase subunit 3"],
                                         "CYTB":
                                            ["CYTB", "cytochrome b", "Cytochrome b", "cytb", "Cytb", "Cyt b",
                                             "Cytochrome b apoenzyme",
                                             "cytochrome b apoenzyme",
                                             "cytochrome b; TAA stop codon appears afterpolyadenylation"
                                             ],
                                         "ND1":
                                            ["ND1", "nd1", "nd 1", "ND 1", "Nd 1",
                                             "NADH dehydrogenase subunit 1",
                                             "NADH hydrogenase subunit 1",
                                             "subunit 1 of the NADH ubiquinone oxidoreductase complex",
                                             "NADH-1", "NADH1"],
                                         "ND2":
                                            ["ND2", "nd2", "nd 2", "ND 2", "Nd 2",
                                             "NADH dehydrogenase subunit 2",
                                             "NADH hydrogenase subunit 2",
                                             "subunit 2 of the NADH ubiquinone oxidoreductase complex",
                                             "#NADH dehydrogenase subunit 2",
                                             "NADH-2", "NADH2"],
                                         "ND3":
                                            ["ND3", "nd3", "nd 3", "ND 3", "Nd 3",
                                             "NADH dehydrogenase subunit 3",
                                             "NADH hydrogenase subunit 3",
                                             "subunit 3 of the NADH ubiquinone oxidoreductase complex",
                                             "NADH-3", "NADH3"],
                                         "ND4":
                                            ["ND4", "nd4", "nd 4", "ND 4", "Nd 4",
                                             "NADH dehydrogenase subunit 4",
                                             "NADH hydrogenase subunit 4",
                                             "subunit 4 of the NADH ubiquinone oxidoreductase complex",
                                             "NADH-4", "NADH4"],
                                         "ND4L":
                                            ["ND4L", "nd4l", "nd 4l", "ND 4l", "Nd 4l",
                                             "NADH dehydrogenase subunit 4L",
                                             "NADH hydrogenase subunit 4L",
                                             "NADH-4L", "NADH4L"],
                                         "ND5":
                                            ["ND5", "nd5", "nd 5", "ND 5", "Nd 5",
                                             "NADH dehydrogenase subunit 5",
                                             "NADH hydrogenase subunit 5",
                                             "subunit 5 of the NADH ubiquinone oxidoreductase complex",
                                             "NADH-5", "NADH5"],
                                         "ND6":
                                            ["ND6", "nd6", "nd 6", "ND 6", "Nd 6",
                                             "NADH dehydrogenase subunit 6",
                                             "NADH hydrogenase subunit 6",
                                             "subunit 6 of the NADH ubiquinone oxidoreductase complex",
                                             "NADH-6", "NADH6",
                                             "NADH dehydrogenase subunit-6"],

                                })