package:
  name: "mavr"
  version: "0.101"
about:
  summary: "Scripts and pipelines"
source:
  path: ../
requirements:
  build:
    - python {{ python }}
    - pip
    - setuptools
    - ete3
    - scipy
    - numpy
    - pandas
    - matplotlib
    - statsmodels
    - biopython
    - pyparsing
    - xmltodict
    - venn
    - bcbio-gff
    - xlsxwriter
    - routoolpa
  run:
    - python
    - scipy
    - numpy
    - pandas
    - matplotlib
    - ete3
    - statsmodels
    - pyparsing
    - xmltodict
    - biopython
    - venn
    - bcbio-gff
    - xlsxwriter
    - routoolpa
build:
  script: python setup.py install