
from Pipelines.GenomeAnnotation.RepeatAnnotation import RepeatAnnotation
from Pipelines.GenomeAnnotation.ProteinCodingGeneAnnotation import ProteinCodingGeneAnnotation

RepeatAnnotation = RepeatAnnotation()
ProteinCodingGeneAnnotation = ProteinCodingGeneAnnotation()
